---
resources:
  - name: ci-docker
    type: git
    source:
      uri: https://github.com/awsz4you241/ci-docker.git
      branch: master
  - name: ci-pipeline
    type: git
    source:
      uri: https://github.com/awsz4you241/ci-pipeline.git
      branch: master
jobs:
  - name: job-docker-build
    plan:
      - get: ci-docker
      - get: ci-pipeline
      - task: task-docker-build
        privileged: true
        file: ci-pipeline/01-task-docker-build.yml
