---
resources:
  - name: resource-docker
    type: git
    source:
      uri: https://github.com/awsz4you241/ci-docker.git
      branch: master
  - name: resource-pipeline
    type: git
    source:
      uri: https://github.com/awsz4you241/ci-pipeline.git
      branch: master
jobs:
  - name: job-docker-build
    plan:
      - get: resource-docker
      - get: resource-pipeline
      - task: task-docker-build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: docker}           
          run:
            path: ci-docker/01-docker-build.sh
